[package]
name = "echo"
version = "0.1.0"
authors = ["AWS s2n"]
edition = "2021"

[dependencies]
s2n-quic = { version = "1"}
tokio = { version = "1", features = ["full"] }

[workspace]
members = ["."]
